# 生产环境Docker Compose配置
version: "3.8"

services:
  # PostgreSQL数据库
  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.production
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend-network
    ports:
      - "5432:5432"

  # 数据库管理工具
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    networks:
      - backend-network
    ports:
      - "8080:8080"

  # 后端预启动服务 - 负责数据库迁移和初始化
  prestart:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: bash scripts/prestart.sh
    env_file:
      - .env.production
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - PROJECT_NAME=${PROJECT_NAME}
    networks:
      - backend-network
    restart: "no"

  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
      prestart:
        condition: service_completed_successfully
    env_file:
      - .env.production
    environment:
      - DOMAIN=${DOMAIN}
      - FRONTEND_HOST=http://192.168.2.201:3001
      - ENVIRONMENT=production
      - PROJECT_NAME=${PROJECT_NAME}
      - BACKEND_CORS_ORIGINS=["http://localhost","http://localhost:3000","http://localhost:3001","http://localhost:5173","http://localhost:8000","http://192.168.2.201","http://192.168.2.201:3000","http://192.168.2.201:3001","http://192.168.2.201:5173","http://192.168.2.201:8000"]
      - SECRET_KEY=${SECRET_KEY}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # 邮件配置
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      # 监控配置
      - SENTRY_DSN=${SENTRY_DSN}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/api/v1/utils/health-check/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend-network
      - frontend-network
    ports:
      - "8000:8000"

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost}
        - NODE_ENV=production
    restart: always
    depends_on:
      - backend
    networks:
      - frontend-network
    ports:
      - "3000:80"

  # Nginx反向代理 (可选，如果不使用外部负载均衡器)
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "3001:8080"
    networks:
      - frontend-network
      - backend-network

volumes:
  app-db-data:
    driver: local

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge
