// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RoleCreate = {
    /**
     * 角色名称
     */
    name: string;
    /**
     * 创建端
     */
    create_from?: (string | null);
    /**
     * 是否有提示词(Y/N)
     */
    has_prompts?: (string | null);
    /**
     * IP分类ID（关联roles_dir表）
     */
    ip_id: number;
};

export type RoleDirCreate = {
    /**
     * IP分类名称（游戏、动漫、小说）
     */
    ip: string;
    /**
     * IP描述
     */
    ip_desc?: (string | null);
};

export type RoleDirPublic = {
    /**
     * IP分类名称（游戏、动漫、小说）
     */
    ip: string;
    /**
     * IP描述
     */
    ip_desc?: (string | null);
    id: number;
    created_at: (string | null);
};

export type RoleDirsPublic = {
    data: Array<RoleDirPublic>;
    count: number;
};

export type RoleDirUpdate = {
    ip?: (string | null);
    /**
     * IP描述
     */
    ip_desc?: (string | null);
};

export type RolePublic = {
    /**
     * 角色名称
     */
    name: string;
    /**
     * 创建端
     */
    create_from?: (string | null);
    /**
     * 是否有提示词(Y/N)
     */
    has_prompts?: (string | null);
    id: number;
    ip_id: number;
    created_at: (string | null);
    role_dir?: (RoleDirPublic | null);
};

export type RolesPublic = {
    data: Array<RolePublic>;
    count: number;
};

export type RoleTemplateCreate = {
    /**
     * 星图角色ID（关联roles表）
     */
    role_id: number;
    /**
     * 模板名称
     */
    template_name?: (string | null);
    /**
     * 是否激活(Y/N)
     */
    is_active?: (string | null);
};

export type RoleTemplateItemCreate = {
    /**
     * 条目名称
     */
    item_name: string;
    /**
     * 提示词描述
     */
    item_prompt_desc?: (string | null);
    /**
     * 角色模板ID（关联role_template表）
     */
    role_tmp_id: number;
};

export type RoleTemplateItemPublic = {
    /**
     * 条目名称
     */
    item_name: string;
    /**
     * 提示词描述
     */
    item_prompt_desc?: (string | null);
    id: number;
    role_tmp_id: number;
    created_at: (string | null);
    template?: (RoleTemplatePublic | null);
};

export type RoleTemplateItemsPublic = {
    data: Array<RoleTemplateItemPublic>;
    count: number;
};

export type RoleTemplateItemUpdate = {
    item_name?: (string | null);
    /**
     * 提示词描述
     */
    item_prompt_desc?: (string | null);
    /**
     * 角色模板ID（关联role_template表）
     */
    role_tmp_id?: (number | null);
};

export type RoleTemplatePublic = {
    /**
     * 星图角色ID（关联roles表）
     */
    role_id: number;
    /**
     * 模板名称
     */
    template_name?: (string | null);
    /**
     * 是否激活(Y/N)
     */
    is_active?: (string | null);
    id: number;
    created_at: (string | null);
    role?: (RolePublic | null);
};

export type RoleTemplatesPublic = {
    data: Array<RoleTemplatePublic>;
    count: number;
};

export type RoleTemplateUpdate = {
    /**
     * 星图角色ID（关联roles表）
     */
    role_id?: (number | null);
    /**
     * 模板名称
     */
    template_name?: (string | null);
    /**
     * 是否激活(Y/N)
     */
    is_active?: (string | null);
};

export type RoleUpdate = {
    name?: (string | null);
    /**
     * 创建端
     */
    create_from?: (string | null);
    /**
     * 是否有提示词(Y/N)
     */
    has_prompts?: (string | null);
    /**
     * IP分类ID（关联roles_dir表）
     */
    ip_id?: (number | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RoleDirsReadRoleDirsData = {
    /**
     * 搜索IP分类名称（模糊匹配）
     */
    ip?: (string | null);
    /**
     * 搜索IP描述（模糊匹配）
     */
    ipDesc?: (string | null);
    limit?: number;
    skip?: number;
};

export type RoleDirsReadRoleDirsResponse = (RoleDirsPublic);

export type RoleDirsCreateRoleDirData = {
    requestBody: RoleDirCreate;
};

export type RoleDirsCreateRoleDirResponse = (RoleDirPublic);

export type RoleDirsReadRoleDirByIdData = {
    roleDirId: number;
};

export type RoleDirsReadRoleDirByIdResponse = (RoleDirPublic);

export type RoleDirsUpdateRoleDirData = {
    requestBody: RoleDirUpdate;
    roleDirId: number;
};

export type RoleDirsUpdateRoleDirResponse = (RoleDirPublic);

export type RoleDirsDeleteRoleDirData = {
    roleDirId: number;
};

export type RoleDirsDeleteRoleDirResponse = (Message);

export type RolesReadRolesData = {
    /**
     * 搜索创建端（模糊匹配）
     */
    createFrom?: (string | null);
    /**
     * 是否有提示词(Y/N)
     */
    hasPrompts?: (string | null);
    /**
     * 筛选IP分类ID
     */
    ipId?: (number | null);
    limit?: number;
    /**
     * 搜索角色名称（模糊匹配）
     */
    name?: (string | null);
    skip?: number;
};

export type RolesReadRolesResponse = (RolesPublic);

export type RolesCreateRoleData = {
    requestBody: RoleCreate;
};

export type RolesCreateRoleResponse = (RolePublic);

export type RolesReadRoleByIdData = {
    roleId: number;
};

export type RolesReadRoleByIdResponse = (RolePublic);

export type RolesUpdateRoleData = {
    requestBody: RoleUpdate;
    roleId: number;
};

export type RolesUpdateRoleResponse = (RolePublic);

export type RolesDeleteRoleData = {
    roleId: number;
};

export type RolesDeleteRoleResponse = (Message);

export type RoleTemplateItemsReadRoleTemplateItemsData = {
    /**
     * 搜索条目名称（模糊匹配）
     */
    itemName?: (string | null);
    limit?: number;
    /**
     * 角色模板ID筛选
     */
    roleTmpId?: (number | null);
    skip?: number;
};

export type RoleTemplateItemsReadRoleTemplateItemsResponse = (RoleTemplateItemsPublic);

export type RoleTemplateItemsCreateRoleTemplateItemData = {
    requestBody: RoleTemplateItemCreate;
};

export type RoleTemplateItemsCreateRoleTemplateItemResponse = (RoleTemplateItemPublic);

export type RoleTemplateItemsReadRoleTemplateItemByIdData = {
    roleTemplateItemId: number;
};

export type RoleTemplateItemsReadRoleTemplateItemByIdResponse = (RoleTemplateItemPublic);

export type RoleTemplateItemsUpdateRoleTemplateItemData = {
    requestBody: RoleTemplateItemUpdate;
    roleTemplateItemId: number;
};

export type RoleTemplateItemsUpdateRoleTemplateItemResponse = (RoleTemplateItemPublic);

export type RoleTemplateItemsDeleteRoleTemplateItemData = {
    roleTemplateItemId: number;
};

export type RoleTemplateItemsDeleteRoleTemplateItemResponse = (Message);

export type RoleTemplatesReadRoleTemplatesData = {
    /**
     * 激活状态筛选(Y/N)
     */
    isActive?: (string | null);
    limit?: number;
    /**
     * 角色ID筛选
     */
    roleId?: (number | null);
    skip?: number;
    /**
     * 搜索模板名称（模糊匹配）
     */
    templateName?: (string | null);
};

export type RoleTemplatesReadRoleTemplatesResponse = (RoleTemplatesPublic);

export type RoleTemplatesCreateRoleTemplateData = {
    requestBody: RoleTemplateCreate;
};

export type RoleTemplatesCreateRoleTemplateResponse = (RoleTemplatePublic);

export type RoleTemplatesReadRoleTemplateByIdData = {
    roleTemplateId: number;
};

export type RoleTemplatesReadRoleTemplateByIdResponse = (RoleTemplatePublic);

export type RoleTemplatesUpdateRoleTemplateData = {
    requestBody: RoleTemplateUpdate;
    roleTemplateId: number;
};

export type RoleTemplatesUpdateRoleTemplateResponse = (RoleTemplatePublic);

export type RoleTemplatesDeleteRoleTemplateData = {
    roleTemplateId: number;
};

export type RoleTemplatesDeleteRoleTemplateResponse = (Message);

export type UsersReadUsersData = {
    /**
     * 搜索邮箱（模糊匹配）
     */
    email?: (string | null);
    /**
     * 搜索全名（模糊匹配）
     */
    fullName?: (string | null);
    limit?: number;
    /**
     * 用户角色，可选值：superuser, user
     */
    role?: (string | null);
    skip?: number;
    /**
     * 用户状态，可选值：active, inactive
     */
    status?: (string | null);
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);