"""add role_template and role_template_item tables

Revision ID: 84799c4dd8f0
Revises: db60dffe5597
Create Date: 2025-07-28 22:29:54.721211

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84799c4dd8f0'
down_revision = 'db60dffe5597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建role_template表
    op.create_table('role_template',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('is_active', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建role_template_item表
    op.create_table('role_template_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('item_prompt_desc', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('role_tmp_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['role_tmp_id'], ['role_template.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_template_item')
    op.drop_table('role_template')
    # ### end Alembic commands ###
