"""add roles table

Revision ID: db60dffe5597
Revises: e9c8557a2860
Create Date: 2025-07-28 21:54:11.650101

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db60dffe5597'
down_revision = 'e9c8557a2860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
        sa.Column('create_from', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('has_prompts', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('ip_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['ip_id'], ['roles_dir.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
