"""add roles_dir table

Revision ID: e9c8557a2860
Revises: 1a31ce608336
Create Date: 2025-07-28 21:31:33.768177

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9c8557a2860'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_dir',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('ip_desc', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_dir')
    # ### end Alembic commands ###
