/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutVisualJsonEditorImport } from './routes/_layout/visual-json-editor'
import { Route as LayoutTaskCreatRolePromptsImport } from './routes/_layout/task-creat-role-prompts'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutRolesImport } from './routes/_layout/roles'
import { Route as LayoutRoleTemplatesImport } from './routes/_layout/role-templates'
import { Route as LayoutRoleTemplateItemsImport } from './routes/_layout/role-template-items'
import { Route as LayoutRolePromptsImport } from './routes/_layout/role-prompts'
import { Route as LayoutRoleDirsImport } from './routes/_layout/role-dirs'
import { Route as LayoutPromptGeneratorImport } from './routes/_layout/prompt-generator'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutAmiyaEditorImport } from './routes/_layout/amiya-editor'
import { Route as LayoutAdminImport } from './routes/_layout/admin'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutVisualJsonEditorRoute = LayoutVisualJsonEditorImport.update({
  path: '/visual-json-editor',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTaskCreatRolePromptsRoute = LayoutTaskCreatRolePromptsImport.update(
  {
    path: '/task-creat-role-prompts',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRolesRoute = LayoutRolesImport.update({
  path: '/roles',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRoleTemplatesRoute = LayoutRoleTemplatesImport.update({
  path: '/role-templates',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRoleTemplateItemsRoute = LayoutRoleTemplateItemsImport.update({
  path: '/role-template-items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRolePromptsRoute = LayoutRolePromptsImport.update({
  path: '/role-prompts',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutRoleDirsRoute = LayoutRoleDirsImport.update({
  path: '/role-dirs',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPromptGeneratorRoute = LayoutPromptGeneratorImport.update({
  path: '/prompt-generator',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAmiyaEditorRoute = LayoutAmiyaEditorImport.update({
  path: '/amiya-editor',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/amiya-editor': {
      preLoaderRoute: typeof LayoutAmiyaEditorImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/prompt-generator': {
      preLoaderRoute: typeof LayoutPromptGeneratorImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/role-dirs': {
      preLoaderRoute: typeof LayoutRoleDirsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/role-prompts': {
      preLoaderRoute: typeof LayoutRolePromptsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/role-template-items': {
      preLoaderRoute: typeof LayoutRoleTemplateItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/role-templates': {
      preLoaderRoute: typeof LayoutRoleTemplatesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/roles': {
      preLoaderRoute: typeof LayoutRolesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/task-creat-role-prompts': {
      preLoaderRoute: typeof LayoutTaskCreatRolePromptsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/visual-json-editor': {
      preLoaderRoute: typeof LayoutVisualJsonEditorImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutAmiyaEditorRoute,
    LayoutItemsRoute,
    LayoutPromptGeneratorRoute,
    LayoutRoleDirsRoute,
    LayoutRolePromptsRoute,
    LayoutRoleTemplateItemsRoute,
    LayoutRoleTemplatesRoute,
    LayoutRolesRoute,
    LayoutSettingsRoute,
    LayoutTaskCreatRolePromptsRoute,
    LayoutVisualJsonEditorRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
