-- public.alembic_version definition

-- Drop table

-- DROP TABLE public.alembic_version;

CREATE TABLE public.alembic_version ( version_num varchar(32) NOT NULL, CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num));


-- public.role_prompt definition

-- Drop table

-- DROP TABLE public.role_prompt;

CREATE TABLE public.role_prompt ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, role_id int4 NOT NULL, "version" int2 NOT NULL, user_prompt json NOT NULL, is_active bpchar(1) NULL, created_at timestamp NULL, CONSTRAINT role_prompt_pkey PRIMARY KEY (id));
COMMENT ON TABLE public.role_prompt IS '角色提示词';


-- public.role_template definition

-- Drop table

-- DROP TABLE public.role_template;

CREATE TABLE public.role_template ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, role_id int4 NOT NULL, template_name varchar(255) NULL, is_active bpchar(1) NULL, created_at timestamp NULL, CONSTRAINT role_template_pkey PRIMARY KEY (id));
COMMENT ON TABLE public.role_template IS '角色模版';

-- Column comments

COMMENT ON COLUMN public.role_template.role_id IS '星图角色id';


-- public.role_template_item definition

-- Drop table

-- DROP TABLE public.role_template_item;

CREATE TABLE public.role_template_item ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, role_tmp_id int4 NOT NULL, item_name varchar(255) NOT NULL, item_prompt_desc text NULL, created_at timestamp NULL, CONSTRAINT role_template_item_pkey PRIMARY KEY (id));
COMMENT ON TABLE public.role_template_item IS '角色模版条目';


-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, "name" varchar(60) NOT NULL, ip_id int4 NOT NULL, create_from varchar(255) NULL, created_at timestamp NULL, has_prompts bpchar(1) NULL, CONSTRAINT roles_pkey PRIMARY KEY (id));
COMMENT ON TABLE public.roles IS '星图角色';

-- Column comments

COMMENT ON COLUMN public.roles."name" IS '角色名称';
COMMENT ON COLUMN public.roles.ip_id IS '游戏、动漫、小说';
COMMENT ON COLUMN public.roles.create_from IS '创建端';


-- public.roles_dir definition

-- Drop table

-- DROP TABLE public.roles_dir;

CREATE TABLE public.roles_dir ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, ip varchar(255) NOT NULL, ip_desc varchar(255) NULL, created_at timestamp NULL, CONSTRAINT roles_dir_pkey PRIMARY KEY (id));
COMMENT ON TABLE public.roles_dir IS '星图角色分类';

-- Column comments

COMMENT ON COLUMN public.roles_dir.ip IS '游戏、动漫、小说';


-- public.task_creat_role_prompt definition

-- Drop table

-- DROP TABLE public.task_creat_role_prompt;

CREATE TABLE public.task_creat_role_prompt ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, task_name varchar(255) NULL, task_state bpchar(1) NULL, task_cmd json NULL, role_id int4 NULL, role_item_prompt json NULL, created_at timestamp NULL, CONSTRAINT task_creat_role_prompt_pkey PRIMARY KEY (id));
COMMENT ON TABLE public.task_creat_role_prompt IS '角色创建提示词任务';


-- public."user" definition

-- Drop table

-- DROP TABLE public."user";

CREATE TABLE public."user" ( email varchar(255) NOT NULL, is_active bool NOT NULL, is_superuser bool NOT NULL, full_name varchar(255) NULL, hashed_password varchar NOT NULL, id uuid NOT NULL, CONSTRAINT user_pkey PRIMARY KEY (id));
CREATE UNIQUE INDEX ix_user_email ON public."user" USING btree (email);


-- public.item definition

-- Drop table

-- DROP TABLE public.item;

CREATE TABLE public.item ( description varchar(255) NULL, title varchar(255) NOT NULL, id uuid NOT NULL, owner_id uuid NOT NULL, CONSTRAINT item_pkey PRIMARY KEY (id), CONSTRAINT item_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public."user"(id) ON DELETE CASCADE);


